
=encoding utf-8

=head1 QUESTION

以下のスクリプトで、@arrayの内容はどのようになるでしょう。

    my @array = ('a', 'b', 'c');
    @array = @array x 3;

=head1 CHOICES

=over

=item 1.

シンタックスエラー

=item 2.

('abcabcabc')

=item 3.

('333')

=item 4.

('a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c')

=back

=head1 ANSWER

3

=head1 EXPLANATION

C<x> 演算子は文字列やリストの繰り返し演算子ですが、配列に使われた場合、スカラコンテキストで評価されます。
したがって、C<scalar @array> が3度繰り返された C<333> が正解です。

    @array = ('a', 'b', 'c');
    @array = scalar(@array) x 3; # => 333

もしも、配列の中身を繰り返したいのであれば、以下のようにすれば良いでしょう。

    (@array) x 3;

=head1 AUTHOR

Kato Atsushi
http://github.com/ktat

=cut
