=encoding utf-8

=head1 QUESTION

Perlを作った人は？

=head1 CHOICES

=over

=item 1.

Bill Gates

=item 2.

Larry Wall

=item 3.

dan kogai

=item 4.

Tom Christiansen

=back

=head1 ANSWER

2

=head1 EXPLANATION

PerlはLarry Wall氏によって作成されました。
この辺の事はプログラミングPerlという本に書かれています。

Bill Gates氏はマイクロソフトの会長ですが、BASICインタプリタを作っています。dan kogai氏、Tom Christiansen氏は著名なPerl Mongerの一人です。

=head1 AUTHOR

eba**a123
http://minna.cert.yahoo.co.jp/cbrws/
