
=encoding utf-8

=head1 QUESTION

Perlのサブルーチンは引数を C<@_> で受け取りますが、一般的にはこれをサブルーチン内で名前付き変数に代入してから使います。
このとき、正しい方法はどれでしょう。なお、コードの冒頭で C<< use 5.12.0; >> を宣言しているものとします。

=head1 CHOICES

=over

=item 1.

    use 5.12.0;
    sub f {
        my($foo, $bar) = @_;
        ...;
    }

=item 2.

    use 5.12.0;
    sub f {
        local($foo, $bar) = @_;
        ...;
    }

=item 3.

    use 5.12.0;
    sub f {
        state($foo, $bar) = @_;
        ...;
    }

=item 4.

    use 5.12.0;
    sub f { |$foo, $bar|
        ...;
    }

=item 5.

    use 5.12.0;
    sub f {
        var($foo, $bar) = @_;
        ...;
    }

=back

=head1 ANSWER

1

=head1 EXPLANATION

サブルーチン内で変数を宣言するときは必ず1番の C<my> を使います。

2番の C<local> は既に宣言してある変数の値をそのスコープ内でのみ変更するために使うキーワードです。変数を宣言するためのものではありません。

3番の C<state> はプログラムのライフサイクル中一度だけ初期化される変数を宣言します。この機能は Perl 5.10.0 で導入されたもので、 C<< use 5.12.0; >> によっても有効になります。

4番の C<|...|> はRubyにおいてブロック引数を受け取る構文です。

5番の C<var> はJavaScriptで変数を宣言する構文です。

なお、この最初の引数の代入の意味は命名だけではありません。Perlの引数は参照渡しなので、不用意な引数の変更を避けるために手動で値渡しにするという意味もあります。

=head1 AUTHOR

Fuji Goro
http://github.com/gfx

=cut
