=encoding utf-8

=head1 QUESTION

数値の判定についての問題です。

変数 C<$var> にC<0>かC<"0">が入っている。この時、文字列のC<0>ではなく数値のC<0>である判定はどのようにすればよいか？

=head1 CHOICES

=over

=item 1.

    if ($var =~ /\D/)

=item 2.

    if ($var == 0 && $var ne "0")

=item 3.

    if ($var eq "0")

=item 4.

これでは判定できない

=back

=head1 ANSWER

4

=head1 EXPLANATION

変数を比較する場合に、0の比較は常に面倒な事を引き起こします。
従って、(2)ならば可能のような気がしますが、Perlは文脈によって数値と文字列を変換します。

普通は気にしなくて良いと思われます。
簡単に見るならば、L<Devel::Peek> を使ってください。

=head1 AUTHOR

eba**a123
http://minna.cert.yahoo.co.jp/cbrws/
