
=encoding utf-8

=head1 QUESTION

C<$item = ('a', 'b', 'c')> を実行すると、$item には以下のどの値が入るでしょう。

=head1 CHOICES

=over

=item 1.

 3

=item 2.

 'a'

=item 3.

 'c'

=back

=head1 ANSWER

3

=head1 EXPLANATION

3番が正解です。リストをスカラコンテキストで受けた場合、最後の値が戻ります。

=over

=head1 AUTHOR

Kato Atsushi
http://github.com/ktat

=cut
