
=encoding utf-8

=head1 QUESTION

以下のうち、数値 C<255> を表していないものはどれか。

=head1 CHOICES

=over

=item 1.

0xff

=item 2.

0255

=item 3.

2_5_5

=item 4.

0b11111111

=back

=head1 ANSWER

2

=head1 EXPLANATION

多くのプログラミング言語と同様に、Perl でも10進数以外の数値を記述することができます。

C<0> で始まるものは8進数、C<0x> ではじまるものは16進数、C<0b> ではじまるものは二進数として扱われます。

したがって C<0xff>、C<0b11111111>、はどちらも 255 を表します。

0255 は8進数で 173 を表しているので、これが正解です。

また、Perl では整数リテラルにアンダーバーをいれることで大きな数値を読みやすくするという機能があります。
その機能により、C<2_5_5> というのは 255 を意味します。
このような小さな数値で使われることはあまりありませんが、

    1_000_000_000

などの大きな数値を扱う場合に使用すると、視認性をよくすることができます。


=head1 AUTHOR

Daisuke Murase
http://github.com/typester

=cut
