
=encoding utf-8

=head1 QUESTION

Perlのスローガンは以下のうちどれでしょう？

=head1 CHOICES

=over

=item 1.

「一つのことをうまくやれ」

=item 2.

「驚き最小限の法則」

=item 3.

「正しく、美しく、速く(この順番で)」

=item 4.

「推測するな、測定せよ」

=item 5.

「やりかたは一つではない」

=back

=head1 ANSWER

5

=head1 EXPLANATION

「やりかたは一つではない」は TMTOWTDI(There's More Than One Way To Do It; ティムトゥーディ) としてよく知られたPerlのスローガンです。

これに対して「一つのことをうまくやれ」はUNIXのスローガンであり、Pythonのスローガンです。特にPythonはほぼ同じ用途のプログラミング言語ですが、思想はまったく異なるというわけです。

「驚き最小の法則」はUIの設計でよく言われる、人間工学における原則です。

「正しく、美しく、速く(この順番で)」は、書籍『ビューティフル・コード』第五章(Elliotte Rusty Harold)のタイトルで、ソフトウェアにおいてはこの3つがこの順番で重要であると述べています。

「推測するな、測定せよ」は書籍『24時間365日 サーバ/インフラを支える技術』にある言葉で、システムの運用に関して述べています。

=head1 AUTHOR

Fuji Goro
http://github.com/gfx

=cut
