=encoding utf-8

=head1 QUESTION

以下はファイル内のテキスト全体を読み込む処理ですが

    open my $fh, '<', './inputfile' or die "failed to open: $!";
    my $content = do { HERE };
    print $content;

C<HERE> に入るコードは次のうちどれか。

=head1 CHOICES

=over

=item 1.

    <$fh>;

=item 2.

    local $!; <$fh>;

=item 3.

    local $/; <$fh>;

=item 4.

    local $^O = 'MSWin32'; <$fh>;

=back

=head1 ANSWER

3

=head1 EXPLANATION

C<$/> は C<$INPUT_RECORD_SEPARATOR> の別名で、入力レコードのセパレータ文字が指定されます。通常は改行文字になっていますが、これを未指定としファイル全体を1レコードして扱う事でファイル全体を読み込みます。

=head1 AUTHOR

Yasuhiro Matsumoto
http://github.com/mattn

=cut
