=encoding utf-8

=head1 QUESTION

Perlでオブジェクト指向プログラミングを行うために何が必要か答えなさい。

=head1 CHOICES

=over

=item 1.

Visual Perl++

=item 2.

oPerl(Objective Perl)

=item 3.

Ruby

=item 4.

上記以外

=back

=head1 ANSWER

4

=head1 EXPLANATION

Perl5からはオブジェクト指向プログラミングが可能です。このため、Perl以外特に必要ありません。

なお、Visutal Perl++は発売されておりません。
oPerlというものは存在しません。
Rubyはれっきとした言語です。

=head1 AUTHOR

eba**a123
http://minna.cert.yahoo.co.jp/cbrws/

