=encoding utf-8

=head1 QUESTION

Perlの父、Larry Wallが定義するプログラマーの三大美徳にあてはまらないものはどれか？

=head1 CHOICES

=over

=item 1.

怠惰

=item 2.

傲慢

=item 3.

短気

=item 4.

臆病

=back

=head1 ANSWER

4

=head1 EXPLANATION

Larry Wall氏によれば、プログラマの三大美徳とは、無精(怠慢)、短気、傲慢だそうです。

無精というのは、楽をする事です。しかし、目先で手を抜くのではなく、全体の事を考えて手間を惜しまず楽をしましょうという事です。
短気というのは、コンピュータが怠慢な時に感じる怒りです。今後起こりうる事を想定してプログラムに励みましょう。
傲慢というのは、尊大な自尊心を持ちましょうという事です。そのためには、人様に見せて恥ずかしくないプログラムを書かねばなりませんね。

=head1 AUTHOR

eba**a123
http://minna.cert.yahoo.co.jp/cbrws/
