=encoding utf-8

=head1 QUESTION

useとrequireの違いについて以下から正しい物を選択せよ。

=head1 CHOICES

=over

=item 1.

useはランタイムでモジュールを読み込み、requireはコンパイル時に読み込む

=item 2.

useはオールナイトでモジュールを読み込み、requireはパイルダーオン時に読み込む

=item 3.

useはコンパイル時にモジュールを読み込み、requireはランタイムで読み込む

=back

=head1 ANSWER

3

=head1 EXPLANATION

useはコンパイル時にモジュールを読み込みます。

    if (0) {
        use Foo;
        # using Foo
    }

ですので上記の場合、Fooというモジュールが存在しない場合はコンパイル時にエラーとなります。
それに比べてrequireはランタイムでモジュールが読み込まれます。

    if ($^O eq 'MSWin32') {
        require Win32::API;
        # using Win32::API
    }

よってOSや処理系によって処理を切り替えたい場合に使えます。
なお、useはコンパイル時に読み込みますので特殊ブロックは C<BEGIN> C<CHECK> C<INIT> を実行してから処理が開始されますが、requireは既にそれらは実行済みですので C<BEGIN> ブロックのみが実行されます。
条件に従って、use相当を行う場合は

    BEGIN {
        require Foo;
        Foo->import();
    }

とする事で同等の動きとなります。またimportの引数がuseに渡す引数に相当します。

=head1 AUTHOR

Yasuhiro Matsumoto
https://github.com/mattn
